''' 389. Find the Difference

Easy    3.5K    409     Companies

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter
at a random position.

Return the letter that was added to t.


Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"
 

Constraints:        0 <= s.length <= 1000
                    t.length == s.length + 1
                    s and t consist of lowercase English letters.
Accepted:           465.8K
Submissions:        773.9K
Acceptance Rate:    60.2%
'''

from collections import Counter


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        cnt = Counter(s)
        # print(cnt)
        for cha in t:
            if cha not in cnt: return cha
            else:
                cnt[cha] -= 1
                if cnt[cha] < 0: return cha


class Solution_v2:
    def findTheDifference(self, s: str, t: str) -> str:
        c = 0
        for cs in s: c ^= ord(cs) #ord is ASCII value
        for ct in t: c ^= ord(ct)
        return chr(c) #chr = convert ASCII into character


def main():
    sol = Solution()
    sol = Solution_v2()

    s, t = "abcd", "abcde"     # Output: "e"
    print(sol.findTheDifference(s, t))


if __name__ == "__main__":
    main()
